version: "3.0"

services:

  db:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: yusif
      POSTGRES_PASSWORD: BTKChat
      POSTGRES_DB: btk_db
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - ./database:/var/lib/postgresql/data
      
  #   networks:
  #     - custom

  # networks:
  #   custom:
  #     driver: bridge



  # redis:
  #   image: redis
  #   container_name: redis_1
  #   restart: always
  #   ports:
  #     - 6379:6379


  adminer:
    image: adminer
    container_name:  adminer
    restart: always
    ports:
      - 8080:8080
