version: "3.0"

services:
  db:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=BTK
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=2023btkChat
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge