"""add user nullable fields

Revision ID: 7f2358261e07
Revises: 82af9b8fbb50
Create Date: 2024-01-31 16:34:04.598093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f2358261e07'
down_revision: Union[str, None] = '82af9b8fbb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'qr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'gender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'gender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'qr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
