"""account alter table drop doctor_id column

Revision ID: 56e848bf99af
Revises: afbf41009fa5
Create Date: 2024-02-20 09:24:42.723353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e848bf99af'
down_revision: Union[str, None] = 'afbf41009fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_doctor_fk', 'account', type_='foreignkey')
    op.drop_column('account', 'doctor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('account_doctor_fk', 'account', 'doctor', ['doctor_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###
