"""create user table 

Revision ID: 6ddc10bbf74a
Revises: 
Create Date: 2024-02-12 17:43:49.540076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ddc10bbf74a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('account',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('last_enter', sa.DateTime(), nullable=False),
    sa.Column('btk_db_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='account_doctor_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('btk_db_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_account_is_active'), 'account', ['is_active'], unique=False)
    op.create_table('doctor',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('speciality_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='doctor_account_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='doctor_creater_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], name='doctor_speciality_fk', onupdate='CASCASE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('account_id', 'speciality_id', name='account_speciality_uc')
    )
    op.create_index(op.f('ix_doctor_is_active'), 'doctor', ['is_active'], unique=False)
    op.create_table('speciality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='speciality_creater_fk', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('accessaccount',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('access_id', sa.Integer(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_id'], ['access.id'], name='accessaccount_access_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='accessaccount_account_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='accessgroup_creater_fk', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'access_id', name='access_account_uc')
    )
    op.create_table('agency',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='creater_agency_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='disease_creater_fk', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('title')
    )
    op.create_table('gender',
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='gender_creater_fk', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('qr',
    sa.Column('qr', sa.String(length=200), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='qr_creater_fk', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr')
    )
    op.create_table('certificate',
    sa.Column('cretificate_id', sa.String(length=64), nullable=False),
    sa.Column('validity', sa.DateTime(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name='certificate_agency', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='cretificate_creater_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='cretificate_doctor_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cretificate_id')
    )
    op.create_table('diagnosis',
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('current_disease', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='diagnosis_account_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], name='disease_diagnosis', onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='diagnosis_doc_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'disease_id', name='diagnosis_account_disease_uc')
    )
    op.create_table('user',
    sa.Column('cookie', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('last_enter', sa.DateTime(), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('qr_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(username) <= 3', name='username_constraint'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='account_user_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], name='user_gender_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['qr_id'], ['qr.id'], name='user_qr_id', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cookie')
    )
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_table('chat',
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('previous_chat_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('speciality_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name='chat_account_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='chat_doctor_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_chat_id'], ['chat.id'], name='previous_chat_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['speciality_id'], ['speciality.id'], name='chat_speciality_fk', onupdate='CASCASE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chat_user_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('previous_chat_id')
    )
    op.create_index(op.f('ix_chat_active'), 'chat', ['active'], unique=False)
    op.create_table('chatuser',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='chatuser_chat_fk', onupdate='CASCASE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='chatuser_user_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rating',
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='rating_chat_fk', onupdate='CASCASE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='rating_doctor_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='rating_user_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('chatuser_id', sa.Integer(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatuser_id'], ['chatuser.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='feedback_creater_fk', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='feedback_doctor_fk', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('chatuser_id', sa.Integer(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatuser_id'], ['chatuser.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creater_id'], ['account.id'], name='message_creater_id', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_text'), 'message', ['text'], unique=False)
    op.create_table('messagestatus',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('received', sa.DateTime(), nullable=False),
    sa.Column('read', sa.DateTime(), nullable=False),
    sa.Column('chatuser_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatuser_id'], ['chatuser.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='message_status', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messagestatus')
    op.drop_index(op.f('ix_message_text'), table_name='message')
    op.drop_table('message')
    op.drop_table('feedback')
    op.drop_table('rating')
    op.drop_table('chatuser')
    op.drop_index(op.f('ix_chat_active'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_table('user')
    op.drop_table('diagnosis')
    op.drop_table('certificate')
    op.drop_table('qr')
    op.drop_table('gender')
    op.drop_table('disease')
    op.drop_table('agency')
    op.drop_table('accessaccount')
    op.drop_table('speciality')
    op.drop_index(op.f('ix_doctor_is_active'), table_name='doctor')
    op.drop_table('doctor')
    op.drop_index(op.f('ix_account_is_active'), table_name='account')
    op.drop_table('account')
    op.drop_table('access')
    # ### end Alembic commands ###
