"""create message table migration

Revision ID: ad42d2bdbe0f
Revises: 2d550120e349
Create Date: 2024-01-19 16:28:20.052209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad42d2bdbe0f'
down_revision: Union[str, None] = '2d550120e349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('text', sa.Integer(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('chatuserr_id', sa.Integer(), nullable=False),
    sa.Column('creater_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatuserr_id'], ['chatuser.id'], ),
    sa.ForeignKeyConstraint(['creater_id'], ['permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messagestatus',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('received', sa.DateTime(), nullable=False),
    sa.Column('read', sa.DateTime(), nullable=False),
    sa.Column('chatuserr_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatuserr_id'], ['chatuser.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messagestatus')
    op.drop_table('message')
    # ### end Alembic commands ###
