"""create Adjacency relationship permission table migrations

Revision ID: f9b072e91d58
Revises: da46c87f6e90
Create Date: 2024-01-19 15:41:03.747445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b072e91d58'
down_revision: Union[str, None] = 'da46c87f6e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('creater_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'permission', 'permission', ['creater_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_column('permission', 'creater_id')
    # ### end Alembic commands ###
