"""add is active to tables

Revision ID: b414b78db4f8
Revises: 3ca1372f7842
Create Date: 2024-01-23 12:06:58.087065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b414b78db4f8'
down_revision: Union[str, None] = '3ca1372f7842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('group', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_active')
    op.drop_column('doctor', 'is_active')
    # ### end Alembic commands ###
