""" create all  tables

Revision ID: 448fdfeba81a
Revises: 
Create Date: 2024-02-13 10:28:34.815258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448fdfeba81a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('account',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('last_enter', sa.DateTime(), nullable=False),
    sa.Column('btk_db_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('btk_db_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_account_is_active'), 'account', ['is_active'], unique=False)
    op.create_table('agency',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate',
    sa.Column('cretificate_id', sa.String(length=64), nullable=False),
    sa.Column('validity', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cretificate_id')
    )
    op.create_table('diagnosis',
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.Column('current_disease', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('title')
    )
    op.create_table('feedback',
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender',
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('message',
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_text'), 'message', ['text'], unique=False)
    op.create_table('messagestatus',
    sa.Column('received', sa.DateTime(), nullable=False),
    sa.Column('read', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr',
    sa.Column('qr', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr')
    )
    op.create_table('rating',
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speciality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('cookie', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('last_enter', sa.DateTime(), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('char_length(username) <= 3', name='username_constraint'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cookie')
    )
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_table('user')
    op.drop_table('speciality')
    op.drop_table('rating')
    op.drop_table('qr')
    op.drop_table('messagestatus')
    op.drop_index(op.f('ix_message_text'), table_name='message')
    op.drop_table('message')
    op.drop_table('gender')
    op.drop_table('feedback')
    op.drop_table('disease')
    op.drop_table('diagnosis')
    op.drop_table('certificate')
    op.drop_table('agency')
    op.drop_index(op.f('ix_account_is_active'), table_name='account')
    op.drop_table('account')
    op.drop_table('access')
    # ### end Alembic commands ###
