"""add column is_active in the permission table

Revision ID: 82af9b8fbb50
Revises: ad032a2873ce
Create Date: 2024-01-25 12:29:52.656165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82af9b8fbb50'
down_revision: Union[str, None] = 'ad032a2873ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission', 'is_active')
    # ### end Alembic commands ###
