""" create foreign key and relationships to user table and create chat, doctor table 

Revision ID: bb165ca448b9
Revises: 010b33982654
Create Date: 2024-02-13 10:46:21.162268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb165ca448b9'
down_revision: Union[str, None] = '010b33982654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('creater_id', sa.Integer(), nullable=False))
    op.create_foreign_key('creater_agency_id', 'agency', 'account', ['creater_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('certificate', sa.Column('agency_id', sa.Integer(), nullable=False))
    op.create_foreign_key('certificate_agency', 'certificate', 'agency', ['agency_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.add_column('diagnosis', sa.Column('disease_id', sa.Integer(), nullable=True))
    op.add_column('diagnosis', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('diagnosis_account_disease_uc', 'diagnosis', ['account_id', 'disease_id'])
    op.create_foreign_key('diagnosis_account_fk', 'diagnosis', 'account', ['account_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('disease_diagnosis', 'diagnosis', 'disease', ['disease_id'], ['id'], onupdate='NO ACTION', ondelete='NO ACTION')
    op.add_column('disease', sa.Column('creater_id', sa.Integer(), nullable=False))
    op.create_foreign_key('disease_creater_fk', 'disease', 'account', ['creater_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('gender', sa.Column('creater_id', sa.Integer(), nullable=True))
    op.create_foreign_key('gender_creater_fk', 'gender', 'account', ['creater_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('messagestatus', sa.Column('message_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'messagestatus', ['message_id'])
    op.create_foreign_key('message_status', 'messagestatus', 'message', ['message_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('qr', sa.Column('creater_id', sa.Integer(), nullable=False))
    op.create_foreign_key('qr_creater_fk', 'qr', 'account', ['creater_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('speciality', sa.Column('creater_id', sa.Integer(), nullable=False))
    op.create_foreign_key('speciality_creater_fk', 'speciality', 'account', ['creater_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('user', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('qr_id', sa.Integer(), nullable=False))
    op.create_foreign_key('account_user_fk', 'user', 'account', ['account_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('user_qr_id', 'user', 'qr', ['qr_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key('user_gender_fk', 'user', 'gender', ['gender_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_gender_fk', 'user', type_='foreignkey')
    op.drop_constraint('user_qr_id', 'user', type_='foreignkey')
    op.drop_constraint('account_user_fk', 'user', type_='foreignkey')
    op.drop_column('user', 'qr_id')
    op.drop_column('user', 'gender_id')
    op.drop_column('user', 'account_id')
    op.drop_constraint('speciality_creater_fk', 'speciality', type_='foreignkey')
    op.drop_column('speciality', 'creater_id')
    op.drop_constraint('qr_creater_fk', 'qr', type_='foreignkey')
    op.drop_column('qr', 'creater_id')
    op.drop_constraint('message_status', 'messagestatus', type_='foreignkey')
    op.drop_constraint(None, 'messagestatus', type_='unique')
    op.drop_column('messagestatus', 'message_id')
    op.drop_constraint('gender_creater_fk', 'gender', type_='foreignkey')
    op.drop_column('gender', 'creater_id')
    op.drop_constraint('disease_creater_fk', 'disease', type_='foreignkey')
    op.drop_column('disease', 'creater_id')
    op.drop_constraint('disease_diagnosis', 'diagnosis', type_='foreignkey')
    op.drop_constraint('diagnosis_account_fk', 'diagnosis', type_='foreignkey')
    op.drop_constraint('diagnosis_account_disease_uc', 'diagnosis', type_='unique')
    op.drop_column('diagnosis', 'account_id')
    op.drop_column('diagnosis', 'disease_id')
    op.drop_constraint('certificate_agency', 'certificate', type_='foreignkey')
    op.drop_column('certificate', 'agency_id')
    op.drop_constraint('creater_agency_id', 'agency', type_='foreignkey')
    op.drop_column('agency', 'creater_id')
    # ### end Alembic commands ###
